[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/health"
  to = "/index.html"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
